config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/tutor_dashboard", to: "pages#tutor_dashboard", as: "tutor_dashboard"

  resources :sessions, only: [:index, :show, :new, :create] do
    resources :payments, only: [:new, :create]
    resources :session_participations, only: [:create]
    resources :chatrooms, only: [:create]
    resources :reviews, only: [:create]
  end
  get 'sessions/:id/live', to: 'sessions#live', as: 'session_live'

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :users, only: [:update]

  get "/become-a-tutor/", to: "users#become_tutor", as: "become_tutor"
  patch "/become-a-tutor/", to: "users#update_to_tutor", as: "update_to_tutor"

  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-btns">

  <div class="col-xs-6 col-md-6">
      <p>© 2017 - All Rights with EduCrew</p>
    </div>
    <div class="col-xs-3 col-md-3">
      <ul>
        <div class="text-align">
          <li><%= link_to t(".btn-facebook", default: ""), "#", class: "fa fa-facebook" %></li>
          <li><%= link_to t(".btn-instagram", default: ""), "#", class: "fa fa-instagram" %></li>
          <li><%= link_to t(".btn-twitter", default: ""), "#", class: "fa fa-twitter" %></li>
          <li><%= link_to t(".btn-linkedin", default: ""), "#", class: "fa fa-linkedin" %></li>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="keep-left">
  <!-- Logo -->
    <ul>
      <li><%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "icon.png" %>
        <% end %>
      </li>
    </ul>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <%= link_to "How it works", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <% if user_signed_in? %>
      <% if current_user.tutor %>
          <%= link_to "Create a session", new_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
          <%= link_to "Become a tutor", become_tutor_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <% if !current_user.tutor %>
        <%= link_to "Student Dashboard", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <% if current_user.tutor? %>
                  <li>
                    <%= link_to tutor_dashboard_path do %>
                      <i class="fa fa-id-card-o"></i>
                      Go to tutor area
                    <% end %>
                  </li>
                <% end %>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                  <% end %>
                </li>
            </ul>
        </div>
      </div>

    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Sign up", "/users/sign_up", class: "navbar-wagon-item navbar-wagon-link " %>
        <%= link_to "Login", "/users/sign_in", class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to t(".login", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to t(".sign-up", default: "Sign up"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
              <li><%= link_to t(".suggest", default: "Suggest a session"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>

        </ul>
    </div>
  </div>
</div>
</div>
</div>