config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'

  get "/dashboard", to: "pages#dashboard", as: "dashboard"
  get "/tutor_dashboard", to: "pages#tutor_dashboard", as: "tutor_dashboard"

  resources :sessions, only: [:index, :show, :new, :create] do
    resources :payments, only: [:new, :create]
    resources :session_participations, only: [:create]
    resources :chatrooms, only: [:create]
    resources :reviews, only: [:create]
  end
  get 'sessions/:id/live', to: 'sessions#live', as: 'session_live'

  resources :chatrooms, only: [:show] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :users, only: [:update]

  get "/become-a-tutor/", to: "users#become_tutor", as: "become_tutor"
  patch "/become-a-tutor/", to: "users#update_to_tutor", as: "update_to_tutor"

  mount Attachinary::Engine => "/attachinary"
  mount ActionCable.server => "/cable"
end

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="dashboard-title">
    <h1 class="text-center">Tutor Dashboard</h1>
  </div>
  <div class="dashboard-content">
    <div class="dashboard-left">
      <div class="tab">
        <ul class="nav nav-tabs sessions-tabs" role="tablist">
          <li role="presentation" class="active session-tab"><a href="#upcoming-sessions" aria-controls="upcoming-sessions" role="tab" data-toggle="tab">Upcoming sessions (<%= @ongoing_sessions.count %>)</a></li>
          <li role="presentation" class="session-tab"><a href="#past-sessions" aria-controls="past-sessions" role="tab" data-toggle="tab">Past Sessions (<%= @over_sessions.count %>)</a></li>
        </ul>
      </div>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="upcoming-sessions">
          <div class="row">
            <% if @ongoing_sessions.empty? %>
              <div class="empty-message">
                <em>No upcoming sessions yet!</em>
              </div>
            <% else %>
              <% @ongoing_sessions.each do |session| %>
                <div class="col-xs-6 col-sm-4 col-md-3">
                  <%= link_to session_path(session) do %>
                    <div class="card">
                      <div class="card-img-top" style="background-image: url('<%= session.tutor.picture %>')">
                      <div class="card-description">
                        <p><%= session.description %></p>
                      </div>
                      </div>
                      <span class="card-author-price"><%= session.tutor.name.upcase %> - $<%= session.price %></span>
                      <p class="card-title"><%= session.title %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="past-sessions">
          <div class="row">
            <% if @over_sessions.empty? %>
              <div class="empty-message">
                <em>No past sessions yet!</em>
              </div>
            <% else %>
              <% @over_sessions.each do |session| %>
                <div class="col-xs-6 col-sm-4 col-md-3">
                  <%= link_to session_path(session) do %>
                    <div class="card">
                      <div class="card-img-top" style="background-image: url('<%= session.tutor.picture %>')">
                        <div class="card-description">
                          <p><%= session.description %></p>
                        </div>
                      </div>
                      <span class="card-author-price"><%= session.tutor.name.upcase %> - $<%= session.price %></span>
                      <p class="card-title"><%= session.title %></p>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="dashboard-right">
    <div class="tutor-session-btn">
      <%= link_to new_session_path class: "tutor-session-btn" do %>
        Create a session
      <% end %>
    </div>
      <div class="wrapper" style="border:1px solid rgba(1,1,1,0.6);; margin:26px; padding:38px; height:400px;">
        <div class="table-title">
          <p style="font-weight: bold; color:rgba(1,1,1,0.6);">Tutoring summary</p>
            <p style="color:rgba(1,1,1,0.4); border-bottom: 1px solid grey; padding-bottom: 4px; color:rgba(1,1,1,0.5);">Check back for the tutoring stats when you have the first session</p>
        </div>
        <div class="table-earnings">
          <p class="alignleft" style="color:rgba(1,1,1,0.5);">August earnings</p>
          <p class="alignright" style="color:#C37F63">$0.00</p>
          <p class="alignleft" style="color:rgba(1,1,1,0.5);">30-day views</p>
          <p class="alignright" style="color:#C37F63">0</p>
        </div>
        <div class="table-ratings">
          <p class="alignleft" style="border-top: 1px solid grey; padding-top: 4px; color:rgba(1,1,1,0.5);">Overall rating No reviews</p>
          <p class="alignleft" style="color:rgba(1,1,1,0.5);">Total reviews</p>
          <p class="alignright" style="color:#C37F63">0</p>
          <p class="alignleft" style="color:rgba(1,1,1,0.5);">5-star reviews</p>
          <p class="alignright" style="color:#C37F63">0%</p>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal -->
<%#= link_to "#", class: "btn btn-default", data: { toggle: "modal" , target: "#myModal" } do %>
  <!-- <i class="fa fa-wrench"></i> -->
<%# end %>
<!-- <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">

        <%#= simple_form_for(current_user) do |f| %>
          <%#= f.input :first_name %>
          <%#= f.input :photo, as: :attachinary %>

          <%#= f.submit %>
          <%# end %>

      </div>
    </div>
  </div>
</div> -->

app/views/pages/home.html.erb
<div class="homepage-banner">
  <div class="title-homepage">
    <h1>STUDY SMARTER, NOT HARDER</h1>
      <p>Group tutoring sessions suited to your course</p>
  </div>
  <div class="home-search-form">
    <%= form_tag sessions_path, method: 'get', enforce_utf8: false, class: "home-search-form-two" do %>
      <%= text_field_tag :subject, "", placeholder: 'Subject', class: "home-search-btn home-subject" %>
      <%= text_field_tag :university, "", placeholder: 'University', class: "home-search-btn home-university" %>
      <%= submit_tag "Find a session", class: "home-submit-btn btn", name: nil %>
    <% end %>
  </div>
</div>

app/views/pages/tutor_dashboard.html.erb
<div class="container">

  <div class="dashboard-title">
    <h1 class="text-center">Tutor Dashboard</h1>
  </div>

  <div class="dashboard-content">
    <div class="dashboard-left">
      <div class="tab">
        <ul class="nav nav-tabs sessions-tabs" role="tablist">
          <li role="presentation" class="active session-tab"><a href="#upcoming-sessions" aria-controls="upcoming-sessions" role="tab" data-toggle="tab">Upcoming sessions (<%= @ongoing_sessions.count %>)</a></li>
          <li role="presentation" class="session-tab"><a href="#past-sessions" aria-controls="past-sessions" role="tab" data-toggle="tab">Past Sessions (<%= @over_sessions.count %>)</a></li>
        </ul>
      </div>
      <div class="tab-content dash-cards">
        <div role="tabpanel" class="tab-pane active" id="upcoming-sessions">
          <div class="row">
            <% if @ongoing_sessions.empty? %>
              <div class="empty-message">
                <em>No upcoming sessions yet!</em>
              </div>
            <% else %>
              <% @ongoing_sessions.each do |session| %>
                <div class="col-xs-6">
                  <%= link_to session_path(session), class: "card-student-dashboard-link" do %>
                    <div class="card" style= "background: linear-gradient(to right,<%= session.get_color(session.subject) %>)">
                      <div class="card-top">
                        <div class="card-subject">
                          # <%= session.subject %>
                        </div>
                        <div class="card-avatar">
                          <%= image_tag session.tutor.picture, class: "small-card-avatar" %>
                        </div>
                          <div class="main-title">
                            <div class="card-title">
                              <%= session.title %>
                            </div>
                            <div class="card-university">
                              <%= session.university %>
                            </div>
                          </div>
                        </div>
                        <div class="card-details">
                          <div class="card-date-duration">
                            <div class="card-date flex-bottom">
                                <i class="fa fa-clock-o"></i><%= session.date.strftime("%A, %e %B") %> - <%= session.time.strftime("%H:%M") %>
                            </div>
                            <div class="card-duration flex-bottom">
                              <i class="fa fa-hourglass-half"></i> <%= session.duration %>
                            </div>
                          </div>
                          <div class="card-price">
                            <%= humanized_money_with_symbol(session.price) %>
                          </div>
                        </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="past-sessions">
          <div class="row">
            <% if @over_sessions.empty? %>
              <div class="empty-message">
                <em>No past sessions yet!</em>
              </div>
            <% else %>
              <% @over_sessions.each do |session| %>
                <div class="col-xs-6">
                  <%= link_to session_path(session), class: "card-student-dashboard-link" do %>
                    <div class="card" style= "background: linear-gradient(to right,<%= session.get_color(session.subject) %>)">
                      <div class="card-top">
                        <div class="card-subject">
                          # <%= session.subject %>
                        </div>
                        <div class="card-avatar">
                          <%= image_tag session.tutor.picture, class: "small-card-avatar" %>
                        </div>
                          <div class="main-title">
                            <div class="card-title">
                              <%= session.title %>
                            </div>
                            <div class="card-university">
                              <%= session.university %>
                            </div>
                          </div>
                        </div>
                        <div class="card-details">
                          <div class="card-date-duration">
                            <div class="card-date flex-bottom">
                                <i class="fa fa-clock-o"></i><%= session.date.strftime("%A, %e %B") %> - <%= session.time.strftime("%H:%M") %>
                            </div>
                            <div class="card-duration flex-bottom">
                              <i class="fa fa-hourglass-half"></i> <%= session.duration %>
                            </div>
                          </div>
                          <div class="card-price">
                            <%= humanized_money_with_symbol(session.price) %>
                          </div>
                        </div>
                    </div>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="dashboard-right">
    <div class="tutor-session-btn">
      <%= link_to new_session_path class: "tutor-session-btn" do %>
        Create a session
      <% end %>
    </div>
      <div class="wrapper" style="border:1px solid rgba(1,1,1,0.6);; margin:26px; padding:38px;">
        <div class="table-title">
          <p style="font-weight: bold; color:rgba(1,1,1,0.6);">Tutoring summary</p>
            <p style="color:rgba(1,1,1,0.4);">Check back for the tutoring stats when you have the first session</p>
        </div>
        <div class="table-earnings">
          <p style="border-top: 1px solid grey; padding-top: 4px; color:rgba(1,1,1,0.5);">August earnings <a href="#" style="color:#C37F63">$42.00</a></p>
          <p style="color:rgba(1,1,1,0.5);">30-day view <a href="#" style="color:#C37F63">82</a></p>
        </div>
        <div class="table-ratings">
          <p style="border-top: 1px solid grey; padding-top: 4px; color:rgba(1,1,1,0.5);">Overall rating No reviews</p>
          <p style="color:rgba(1,1,1,0.5);">Total reviews <a href="#" style="color:#C37F63">12</a></p>
          <p style="color:rgba(1,1,1,0.5);">5-star reviews <a href="#" style="color:#C37F63">60%</a></p>
        </div>
      </div>
    </div>
  </div>
</div>